# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  schedule:
    - cron: '0 17 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: GitHub metrics as SVG image
        uses: lowlighter/metrics@v3.3
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
#           plugin_followup: yes
#           plugin_isocalendar: yes
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
#           plugin_habits_charts: yes
          config_timezone: Korea/Seoul
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_skipped: cgpathos.github.io
#           plugin_languages_colors: "0:orange, javascript:#ff0000, ..." # Make most used languages orange and JavaScript red
          plugin_languages_details: bytes-size, percentage
#           plugin_languages_threshold: 2%
          #'plugin_languages_threshold', valid inputs are ['base', 'repositories', 'repositories_forks', 'token', 'user', 'committer_token', 'committer_branch', 'filename', 'optimize', 'setup_community_templates', 'template', 'query', 'config_timezone', 'config_order', 'config_animations', 'config_padding', 'config_output', 'plugins_errors_fatal', 'debug', 'verify', 'debug_flags', 'dryrun', 'use_mocked_data', 'use_prebuilt_image', 'plugin_activity', 'plugin_activity_limit', 'plugin_activity_days', 'plugin_activity_filter', 'plugin_anilist', 'plugin_anilist_medias', 'plugin_anilist_sections', 'plugin_anilist_limit', 'plugin_anilist_shuffle', 'plugin_anilist_user', 'plugin_followup', 'plugin_gists', 'plugin_habits', 'plugin_habits_from', 'plugin_habits_days', 'plugin_habits_facts', 'plugin_habits_charts', 'plugin_isocalendar', 'plugin_isocalendar_duration', 'plugin_languages', 'plugin_languages_ignored', 'plugin_languages_skipped', 'plugin_languages_colors', 'plugin_languages_details', 'plugin_lines', 'plugin_music', 'plugin_music_provider', 'plugin_music_token', 'plugin_music_mode', 'plugin_music_playlist', 'plugin_music_limit', 'plugin_music_user', 'plugin_pagespeed', 'plugin_pagespeed_url', 'plugin_pagespeed_detailed', 'plugin_pagespeed_screenshot', 'plugin_pagespeed_token', 'plugin_people', 'plugin_people_limit', 'plugin_people_size', 'plugin_people_types', 'plugin_people_thanks', 'plugin_people_identicons', 'plugin_posts', 'plugin_posts_source', 'plugin_posts_limit', 'plugin_posts_user', 'plugin_projects', 'plugin_projects_limit', 'plugin_projects_repositories', 'plugin_projects_descriptions', 'plugin_stargazers', 'plugin_stars', 'plugin_stars_limit', 'plugin_topics', 'plugin_topics_mode', 'plugin_topics_sort', 'plugin_topics_limit', 'plugin_traffic', 'plugin_tweets', 'plugin_tweets_token', 'plugin_tweets_limit', 'plugin_tweets_user']
          
          
          
